const units = [
  "zéro",
  "un",
  "deux",
  "trois",
  "quatre",
  "cinq",
  "six",
  "sept",
  "huit",
  "neuf",
];
const teens = ["dix", "onze", "douze", "treize", "quatorze", "quinze", "seize"];
const tens = [
  "",
  "",
  "vingt",
  "trente",
  "quarante",
  "cinquante",
  "soixante",
  "soixante-dix",
  "quatre-vingts",
  "quatre-vingt-dix",
];
const numberRange = {
  NEGATIVE_TO_MILLION: "NEGATIVE_TO_MILLION",
  ZERO_TO_NINE: "ZERO_TO_NINE",
  TEN_TO_SIXTEEN: "TEN_TO_SIXTEEN",
  SEVENTEEN_TO_NINETEEN: "SEVENTEEN_TO_NINETEEN",
  TWENTY_TO_SIXTY_NINE: "TWENTY_TO_SIXTY_NINE",
  SEVENTY: "SEVENTY",
  SEVENTY_ONE_TO_SEVENTY_NINE: "SEVENTY_ONE_TO_SEVENTY_NINE",
  EIGHTY: "EIGHTY",
  EIGHTY_ONE_TO_EIGHTY_NINE: "EIGHTY_ONE_TO_EIGHTY_NINE",
  NINETY: "NINETY",
  NINETY_ONE_TO_NINETY_NINE: "NINETY_ONE_TO_NINETY_NINE",
  HUNDRED_TO_ONE_NINETY_NINE: "HUNDRED_TO_ONE_NINETY_NINE",
  TWO_HUNDRED_TO_NINE_HUNDRED_NINETY_NINE:
    "TWO_HUNDRED_TO_NINE_HUNDRED_NINETY_NINE",
  THOUSAND_TO_ONE_THOUSAND_NINE_HUNDRED_NINETY_NINE:
    "THOUSAND_TO_ONE_THOUSAND_NINE_HUNDRED_NINETY_NINE",
  TWO_THOUSAND_TO_NINE_THOUSAND_NINE_HUNDRED_NINETY_NINE:
    "TWO_THOUSAND_TO_NINE_THOUSAND_NINE_HUNDRED_NINETY_NINE",
  TEN_THOUSAND_TO_NINETY_NINE_THOUSAND_NINE_HUNDRED_NINETY_NINE:
    "TEN_THOUSAND_TO_NINETY_NINE_THOUSAND_NINE_HUNDRED_NINETY_NINE",
  HUNDRED_THOUSAND_TO_NINE_HUNDRED_NINETY_NINE_THOUSAND_NINE_HUNDRED_NINETY_NINE:
    "HUNDRED_THOUSAND_TO_NINE_HUNDRED_NINETY_NINE_THOUSAND_NINE_HUNDRED_NINETY_NINE",
};
module.exports = {
  units,
  teens,
  tens,
  numberRange,
};
